/**
 * Central notification type constants and payload shape for operational notifications.
 * Event types are mapped to Airtable via lib/notifications-schema EVENT_TYPE_TO_AIRTABLE.
 */

import type { NotificationEventType, NotificationPriority } from "@/types";

/** Event type constants for operational intelligence. */
export const NOTIFICATION_EVENT = {
  SHIFT_STARTED: "shift_started" as const,
  SHIFT_ENDED: "shift_ended" as const,
  SHIFT_LATE: "shift_late" as const,
  SHIFT_NO_SHOW: "shift_no_show" as const,
  SHIFT_OVERTIME: "shift_overtime" as const,
  SHIFT_RUNNING_LONG: "shift_running_long" as const,
  SHIFT_STARTING_SOON: "shift_starting_soon" as const,
  CHATTER_NO_MODELS: "chatter_no_models" as const,
  BREAK_STARTED: "break_started" as const,
  BREAK_ENDED: "break_ended" as const,
  BREAK_EXCEEDED: "break_exceeded" as const,
  BREAK_TOO_LONG: "break_too_long" as const,
  TASK_STARTED: "task_started" as const,
  TASK_FINISHED: "task_finished" as const,
  TASK_SHIFT_STARTED: "task_shift_started" as const,
  TASK_SHIFT_ENDED: "task_shift_ended" as const,
  TASK_COMPLETED: "task_completed" as const,
  TASK_OVERDUE: "task_overdue" as const,
  TASKS_NOT_STARTED: "tasks_not_started" as const,
  VA_TASK_REMINDER: "va_task_reminder" as const,
  VA_TASK_ASSIGNED: "va_task_assigned" as const,
  PHASE_TASK_COMPLETED: "phase_task_completed" as const,
  PHASE_COMPLETED: "phase_completed" as const,
  PHASE_OVERDUE: "phase_overdue" as const,
  ALL_PHASES_COMPLETED: "all_phases_completed" as const,
  MODEL_BECAME_FREE: "model_became_free" as const,
  MODEL_TAKEN: "model_taken" as const,
  MODEL_LIVE_STARTED: "model_live_started" as const,
  MODEL_LIVE_ENDED: "model_live_ended" as const,
  MODEL_LIVE_SCHEDULED: "model_live_scheduled" as const,
  MODEL_MISSED_LIVE: "model_missed_live" as const,
  MODEL_CONTENT_COMPLETED: "model_content_completed" as const,
  MODEL_CONTENT_SCHEDULED: "model_content_scheduled" as const,
  MODEL_CONTENT_REQUEST_CREATED: "model_content_request_created" as const,
  MODEL_CONTENT_REQUEST_REVIEWED: "model_content_request_reviewed" as const,
  VA_CONTENT_ASSIGNED: "va_content_assigned" as const,
  VA_CONTENT_SCHEDULED: "va_content_scheduled" as const,
  VA_CONTENT_COMPLETED: "va_content_completed" as const,
  CUSTOM_REQUEST_UPLOADED: "custom_request_uploaded" as const,
  PERIOD_3_DAY_REMINDER: "period_3_day_reminder" as const,
  PERIOD_PREDICTED_DAY: "period_predicted_day" as const,
  PERIOD_CONFIRMED_EARLY: "period_confirmed_early" as const,
  PERIOD_OVERDUE: "period_overdue" as const,
  PERIOD_PREDICTION_RESET: "period_prediction_reset" as const,
  WHALE_REGISTERED: "whale_registered" as const,
  WHALE_ASSIGNED: "whale_assigned" as const,
  WHALE_SPENT: "whale_spent" as const,
  CUSTOM_REQUEST_CREATED: "custom_request_created" as const,
  CUSTOM_REQUEST_UPDATED: "custom_request_updated" as const,
  CUSTOM_REQUEST_SUBMITTED: "custom_request_submitted" as const,
  CUSTOM_STATUS_CHANGED: "custom_status_changed" as const,
  CUSTOM_APPROVED: "custom_approved" as const,
  CUSTOM_REJECTED: "custom_rejected" as const,
  CUSTOM_DECLINED: "custom_declined" as const,
  CUSTOM_EDITED: "custom_edited" as const,
  CUSTOM_UPLOADED: "custom_uploaded" as const,
  CUSTOM_SCHEDULED: "custom_scheduled" as const,
  CUSTOM_DEADLINE_APPROACHING: "custom_deadline_approaching" as const,
  CUSTOM_OVERDUE: "custom_overdue" as const,
  FORM_SUBMITTED: "form_submitted" as const,
  SCHEDULE_UPDATED: "schedule_updated" as const,
  WEEKLY_AVAILABILITY_FRIDAY_REMINDER: "weekly_availability_friday_reminder" as const,
  AVAILABILITY_SUBMITTED: "availability_submitted" as const,
  SYSTEM_ALERT: "system_alert" as const,
  USER_CREATED: "user_created" as const,
  ROLE_CHANGED: "role_changed" as const,
  ACCOUNT_DELETED: "account_deleted" as const,
  DAILY_SUMMARY: "daily_summary" as const,
  POINTS_AWARDED: "points_awarded" as const,
  LEVEL_UP: "level_up" as const,
  SPIN_AVAILABLE: "spin_available" as const,
  CHALLENGE_COMPLETED: "challenge_completed" as const,
  SPIN_RESULT: "spin_result" as const,
  SOP_ACADEMY_REMINDER: "sop_academy_reminder" as const,
  SOP_ACADEMY_TRAINING_COMPLETE: "sop_academy_training_complete" as const,
  SOP_ACADEMY_SIGNED_OFF: "sop_academy_signed_off" as const,
  BILLING_CYCLE_ANNOUNCED: "billing_cycle_announced" as const,
  BILLING_DUE_REMINDER: "billing_due_reminder" as const,
  PAYMENT_SUBMITTED: "payment_submitted" as const,
  BILLING_PAYMENT_SUBMITTED: "billing_payment_submitted" as const,
  PAYMENT_CONFIRMED: "payment_confirmed" as const,
  PAYMENT_REJECTED: "payment_rejected" as const,
  EXPENSE_APPROVED: "expense_approved" as const,
  EXPENSE_REJECTED: "expense_rejected" as const,
  CHATTER_MISTAKE: "chatter_mistake" as const,
  CHATTER_MISTAKE_REVIEWED: "chatter_mistake_reviewed" as const,
  FINE_ISSUED: "fine_issued" as const,
  BONUS_AWARDED: "bonus_awarded" as const,
  FINE_BONUS_REVIEWED: "fine_bonus_reviewed" as const,
  SHADOWBAN_REPORT: "shadowban_report" as const,
  SHADOWBAN_SUBMITTED: "shadowban_submitted" as const,
  SHADOWBAN_RESOLVED: "shadowban_resolved" as const,
  SHADOWBAN_LIFTED_REPORTED: "shadowban_lifted_reported" as const,
  SOP_QUIZ_PASSED: "sop_quiz_passed" as const,
  SOP_QUIZ_FAILED: "sop_quiz_failed" as const,
  SCHEDULE_PUBLISHED: "schedule_published" as const,
  LOGIN_NEW_DEVICE: "login_new_device" as const,
  PASSWORD_CHANGED: "password_changed" as const,
  // Admin monitoring variants (paired with personal events above)
  SHIFT_STARTED_ADMIN: "shift_started_admin" as const,
  SHIFT_ENDED_ADMIN: "shift_ended_admin" as const,
  SHIFT_LATE_ADMIN: "shift_late_admin" as const,
  SHIFT_NO_SHOW_ADMIN: "shift_no_show_admin" as const,
  SHIFT_OVERTIME_ADMIN: "shift_overtime_admin" as const,
  SHIFT_RUNNING_LONG_ADMIN: "shift_running_long_admin" as const,
  CHATTER_NO_MODELS_ADMIN: "chatter_no_models_admin" as const,
  BREAK_STARTED_ADMIN: "break_started_admin" as const,
  BREAK_ENDED_ADMIN: "break_ended_admin" as const,
  BREAK_EXCEEDED_ADMIN: "break_exceeded_admin" as const,
  BREAK_TOO_LONG_ADMIN: "break_too_long_admin" as const,
  TASK_STARTED_ADMIN: "task_started_admin" as const,
  TASK_FINISHED_ADMIN: "task_finished_admin" as const,
  TASK_SHIFT_STARTED_ADMIN: "task_shift_started_admin" as const,
  TASK_SHIFT_ENDED_ADMIN: "task_shift_ended_admin" as const,
  TASK_COMPLETED_ADMIN: "task_completed_admin" as const,
  TASK_OVERDUE_ADMIN: "task_overdue_admin" as const,
  TASKS_NOT_STARTED_ADMIN: "tasks_not_started_admin" as const,
  PHASE_TASK_COMPLETED_ADMIN: "phase_task_completed_admin" as const,
  PHASE_COMPLETED_ADMIN: "phase_completed_admin" as const,
  PHASE_OVERDUE_ADMIN: "phase_overdue_admin" as const,
  ALL_PHASES_COMPLETED_ADMIN: "all_phases_completed_admin" as const,
  MODEL_BECAME_FREE_ADMIN: "model_became_free_admin" as const,
  MODEL_TAKEN_ADMIN: "model_taken_admin" as const,
  MODEL_LIVE_STARTED_ADMIN: "model_live_started_admin" as const,
  MODEL_LIVE_ENDED_ADMIN: "model_live_ended_admin" as const,
  MODEL_MISSED_LIVE_ADMIN: "model_missed_live_admin" as const,
  MODEL_CONTENT_COMPLETED_ADMIN: "model_content_completed_admin" as const,
  MODEL_CONTENT_SCHEDULED_ADMIN: "model_content_scheduled_admin" as const,
  VA_CONTENT_ASSIGNED_ADMIN: "va_content_assigned_admin" as const,
  VA_CONTENT_SCHEDULED_ADMIN: "va_content_scheduled_admin" as const,
  VA_CONTENT_COMPLETED_ADMIN: "va_content_completed_admin" as const,
  CUSTOM_REQUEST_UPLOADED_ADMIN: "custom_request_uploaded_admin" as const,
  WHALE_REGISTERED_ADMIN: "whale_registered_admin" as const,
  WHALE_ASSIGNED_ADMIN: "whale_assigned_admin" as const,
  WHALE_FOLLOWUP_ADMIN: "whale_followup_admin" as const,
  WHALE_SPENT_ADMIN: "whale_spent_admin" as const,
  WHALE_SESSION_SUBMITTED_ADMIN: "whale_session_submitted_admin" as const,
  CUSTOM_REQUEST_CREATED_ADMIN: "custom_request_created_admin" as const,
  CUSTOM_REQUEST_UPDATED_ADMIN: "custom_request_updated_admin" as const,
  CUSTOM_REQUEST_SUBMITTED_ADMIN: "custom_request_submitted_admin" as const,
  CUSTOM_STATUS_CHANGED_ADMIN: "custom_status_changed_admin" as const,
  CUSTOM_APPROVED_ADMIN: "custom_approved_admin" as const,
  CUSTOM_REJECTED_ADMIN: "custom_rejected_admin" as const,
  CUSTOM_DECLINED_ADMIN: "custom_declined_admin" as const,
  CUSTOM_EDITED_ADMIN: "custom_edited_admin" as const,
  CUSTOM_UPLOADED_ADMIN: "custom_uploaded_admin" as const,
  CUSTOM_SCHEDULED_ADMIN: "custom_scheduled_admin" as const,
  CUSTOM_DEADLINE_APPROACHING_ADMIN: "custom_deadline_approaching_admin" as const,
  CUSTOM_OVERDUE_ADMIN: "custom_overdue_admin" as const,
  FORM_SUBMITTED_ADMIN: "form_submitted_admin" as const,
  SCHEDULE_UPDATED_ADMIN: "schedule_updated_admin" as const,
  AVAILABILITY_SUBMITTED_ADMIN: "availability_submitted_admin" as const,
  USER_CREATED_ADMIN: "user_created_admin" as const,
  POINTS_AWARDED_ADMIN: "points_awarded_admin" as const,
  LEVEL_UP_ADMIN: "level_up_admin" as const,
  CHALLENGE_COMPLETED_ADMIN: "challenge_completed_admin" as const,
  SPIN_RESULT_ADMIN: "spin_result_admin" as const,
  SOP_ACADEMY_TRAINING_COMPLETE_ADMIN: "sop_academy_training_complete_admin" as const,
  SOP_ACADEMY_SIGNED_OFF_ADMIN: "sop_academy_signed_off_admin" as const,
  PAYMENT_SUBMITTED_ADMIN: "payment_submitted_admin" as const,
  BILLING_PAYMENT_SUBMITTED_ADMIN: "billing_payment_submitted_admin" as const,
  EXPENSE_APPROVED_ADMIN: "expense_approved_admin" as const,
  EXPENSE_REJECTED_ADMIN: "expense_rejected_admin" as const,
  CHATTER_MISTAKE_ADMIN: "chatter_mistake_admin" as const,
  CHATTER_MISTAKE_REVIEWED_ADMIN: "chatter_mistake_reviewed_admin" as const,
  FINE_ISSUED_ADMIN: "fine_issued_admin" as const,
  BONUS_AWARDED_ADMIN: "bonus_awarded_admin" as const,
  FINE_BONUS_REVIEWED_ADMIN: "fine_bonus_reviewed_admin" as const,
  SHADOWBAN_REPORT_ADMIN: "shadowban_report_admin" as const,
  SHADOWBAN_SUBMITTED_ADMIN: "shadowban_submitted_admin" as const,
  SHADOWBAN_RESOLVED_ADMIN: "shadowban_resolved_admin" as const,
  SHADOWBAN_LIFTED_REPORTED_ADMIN: "shadowban_lifted_reported_admin" as const,
  PERIOD_OVERDUE_ADMIN: "period_overdue_admin" as const,
  BILLING_CYCLE_ANNOUNCED_ADMIN: "billing_cycle_announced_admin" as const,
  SOP_QUIZ_PASSED_ADMIN: "sop_quiz_passed_admin" as const,
  SCHEDULE_PUBLISHED_ADMIN: "schedule_published_admin" as const,
} satisfies Record<string, NotificationEventType>;

/** Default priority by event type for operational alerts. Callers can override. */
export const DEFAULT_PRIORITY_BY_EVENT: Partial<Record<NotificationEventType, NotificationPriority>> = {
  shift_overtime: "high",
  chatter_no_models: "high",
  shift_starting_soon: "high",
  weekly_availability_friday_reminder: "high",
  break_exceeded: "high",
  break_too_long: "high",
  model_missed_live: "critical",
  task_overdue: "high",
  tasks_not_started: "high",
  va_task_reminder: "high",
  phase_task_completed: "normal",
  phase_completed: "normal",
  phase_overdue: "high",
  all_phases_completed: "high",
  custom_deadline_approaching: "high",
  custom_overdue: "critical",
  custom_approved: "normal",
  custom_rejected: "normal",
  custom_request_created: "high",
  custom_request_submitted: "high",
  /** Live start: higher default so assigned chatters are more likely to receive push (e.g. vs critical_only). */
  model_live_started: "high",
  model_live_ended: "normal",
  model_live_scheduled: "high",
  task_completed: "normal",
  model_content_completed: "normal",
  model_content_scheduled: "normal",
  va_content_assigned: "normal",
  va_task_assigned: "normal",
  va_content_scheduled: "normal",
  va_content_completed: "normal",
  model_content_request_created: "high",
  model_content_request_reviewed: "normal",
  custom_request_uploaded: "normal",
  period_3_day_reminder: "normal",
  period_predicted_day: "high",
  period_confirmed_early: "normal",
  period_overdue: "high",
  period_prediction_reset: "normal",
  form_submitted: "normal",
  availability_submitted: "normal",
  schedule_updated: "normal",
  user_created: "low",
  role_changed: "high",
  account_deleted: "critical",
  daily_summary: "normal",
  points_awarded: "normal",
  level_up: "high",
  spin_available: "normal",
  challenge_completed: "normal",
  spin_result: "normal",
  sop_academy_reminder: "normal",
  sop_academy_training_complete: "normal",
  sop_academy_signed_off: "normal",
  billing_cycle_announced: "high",
  billing_due_reminder: "high",
  payment_submitted: "high",
  payment_confirmed: "normal",
  payment_rejected: "high",
  expense_approved: "normal",
  expense_rejected: "normal",
  chatter_mistake: "high",
  chatter_mistake_reviewed: "high",
  shadowban_report: "normal",
  shadowban_submitted: "normal",
  shadowban_resolved: "normal",
  shadowban_lifted_reported: "normal",
  sop_quiz_passed: "normal",
  sop_quiz_failed: "normal",
  schedule_published: "normal",
  login_new_device: "high",
  password_changed: "high",
};

/** Entity types for notifications (entity_type in payload). */
export const NOTIFICATION_ENTITY = {
  SHIFT: "shift",
  TASK_SHIFT: "task_shift",
  VA_TASK: "va_task",
  VA_TASK_PHASE: "va_task_phase",
  VA_TASK_PHASE_ITEM: "va_task_phase_item",
  WHALE: "whale",
  CUSTOM_REQUEST: "custom_request",
  MODEL_CONTENT_REQUEST: "model_content_request",
  PERIOD: "model_period",
  ACCOUNT: "account",
  CHATTER_MISTAKE: "chatter_mistake",
  FINE_BONUS: "fine_bonus",
  SOP_ACADEMY: "sop_academy",
  EXPENSE_REQUEST: "expense_request",
} as const;

/** Priorities. */
export const NOTIFICATION_PRIORITY = {
  LOW: "low" as NotificationPriority,
  NORMAL: "normal" as NotificationPriority,
  HIGH: "high" as NotificationPriority,
  CRITICAL: "critical" as NotificationPriority,
} as const;

/**
 * Payload shape for creating an in-app notification (and optional push).
 * Stored in notifications table; actor context and metadata for rich display.
 */
export type AdminNotificationPayload = {
  event_type: NotificationEventType;
  priority: NotificationPriority;
  title: string;
  body: string;
  entity_type: string;
  entity_id: string;
  actor_user_id?: string;
  actor_name?: string;
  /** Optional structured metadata (e.g. models, shift type, deadline). Stored when Airtable has metadata column. */
  metadata?: Array<{ label: string; value: string }>;
};
